### ISSUE TITLE
Potential QQ Bug

### ISSUE THREAD

**Issue by anthonycanino1** [polyglot-compiler/polyglot#2]
Stumbled across these when using the JL Quasi quoter. The following code was causing the QQ to complain about %LM requiring a list of ClassMember, even though that was what was passed.

```
List<ClassMember> members = new ArrayList<>();
// 
// Some code that populated members
//
ClassDecl cd = qq.parseDecl("public class PandaMode { %LM }", members);
```

Error generated from polyglot
```
Compiler Generated: quasiquote(public class PandaMode { public static final int LOW_MODE = 5{amb}M
 }):1: 
Bad quasiquoting substitution: expected List of ClassMember.
```

I think I happened to hit an edge case with the public API for QQ. The following two methods are from QQ.java.  I think from the code it was intended that this was to be another form for variadic parameters to the subsequent parse call, as the transformation of ```subst.toArray()``` results in the array being passed as variable arguments to parse, not as a single array. Commenting out the second parseDecl forced the List of ClassMember to be passed as a list, which then worked fine.

```
public ClassDecl parseDecl(String fmt, Object... os) {
  return (ClassDecl) parse(DECL, fmt, os);
}

public ClassDecl parseDecl(String fmt, List<?> subst) {
  return (ClassDecl) parse(DECL, fmt, subst.toArray());
}
```

The logic that actually dumped the error is in qq.flex if anyone wants to trace further. qq.flex:471 and qq.flex:101 was were I traced to. I'm happy to fix this myself and submit a pull request if someone can confirm my reasoning is correct.

**Comment by chinawat** [comment]
The problem originated when the Polyglot code was ported to Java 5 (commit 47e88d3, July 2012).  New methods with a signature as reported above were erroneously added to QQ.java.  The correct approach is to maintain lists as lists, because there could be multiple substitutions within the same formatting string, so flattening lists could lead to ambiguous or incorrect substitutions.  Fix applied.

Also, I think the check for empty list at the top of substList() disallows empty substitutions, which might be of some use when you want to have no class members, no arguments to a method call, etc.  I am leaving that in place for now until my claim is verified with an example.

**Comment by liujed** [comment]
Those methods were added to maintain compatibility with extensions that were written before the port to Java 5. Removing those methods (commit e7b718782a751455cf8745b83bf82592685067d4) breaks that compatibility.

**Comment by chinawat** [comment]
A further investigation of the troubling use site reveals an incorrect use of the format string, as in

```java
        String comparison = className + "." + meth + "((%E), (%E))";
        List<Expr> l = new ArrayList<Expr>(2);
        l.add(b.left());
        l.add(b.right());
        return rw.qq().parseExpr(comparison, l);
```

`"((%E), (%E))"` should instead be `"(%LE)"`.  Alternatively, `b.left()` and `b.right()` could be passed to `parseExpr` as two separate arguments.

**Comment by liujed** [comment]
Sure, one can rewrite their extension to account for the now-missing methods, but my main point is those methods have been there for a very long time. (In fact, they turn 12 tomorrow: 97cb9e828aae8a2315258bec64f7c4b009347f44.) Removing these methods risks breaking our users' extensions.

**Comment by liujed** [comment]
Also, the most unfortunate thing about removing those methods is that users can't rely on static type checking to tell them what to fix, since calls to the missing methods now dispatch to the varargs version.

**Comment by andrewcmyers** [comment]
Can't we keep the methods and just deprecate them?

**Comment by liujed** [comment]
Yeah, I think deprecating would be better than removing the methods outright. Then, we can remove them after a few releases down the road.

**Comment by chinawat** [comment]
I don't believe the methods taking a list existed before the port to Java 5 (check aforementioned commit).  Then we have methods that take 1-5 objects, and one that takes an array of objects.  A vararg method--and only that--covers all these cases; a method taking a list has been added in error.  Perhaps this is because we had code that misused the quasiquoter that led to this addition instead of correcting the incorrect use.  It is unfortunate that static checking is not viable for this kind of thing, so deprecation now seems to be the only way to detect that mistake.

**Comment by liujed** [comment]
The list version was added 30 Jun 2003. See line 329 of https://github.com/polyglot-compiler/polyglot/blob/97cb9e828aae8a2315258bec64f7c4b009347f44/src/polyglot/qq/QQ.java

**Comment by chinawat** [comment]
You are correct that the method with that signature existed originally, but it invokes a method that has since been ported (from one taking a list to a vararg taking Object...).  It turns out that retaining both signatures results in a missed case (original issue).  We should have had only one kind of signature after the port to make this correct.  In other words, the port should have transferred the invocation involving a list to the new signature and uncovered the incorrect use.

**Comment by liujed** [comment]
I am fairly certain that the post-port API is 100% compatible with the pre-port API, quirks and all. :) Take `parseExpr`, for example. All I did was replace the 9 methods that took varying numbers of Objects with a single vararg method, and replumb things under the hood so the vararg version was the canonical form (previously, the List version was canonical, and the others were convenience methods that created a List for you). Perhaps I should have deprecated the List version; unfortunately, that didn't occur to me at the time.

I think we should reinstate the List versions of the methods, but deprecate them, as Andrew suggested. In the meantime, as for the OP's issue, the workaround is to wrap the List in an array, so the varargs method is called:

```
List<ClassMember> members = new ArrayList<>();
// 
// Some code that populated members
//
ClassDecl cd = qq.parseDecl("public class PandaMode { %LM }", new Object[] {members});
```

**Comment by liujed** [comment]
Chin, I think the confusion is that calling the List version in the pre-port API doesn't do what you might think it does. The List version took a list of substitutions. If you wanted to substitute a single list, then you had to wrap the list in another list. With the pre-port API, the OP's code example would be:

```
List members = new ArrayList();
// 
// Some code that populated members
//
ClassDecl cd = qq.parseDecl("public class PandaMode { %LM }",
    Collections.singletonList(members));
```
or, alternatively, you had to call the version that took a single Object explicitly:
```
// ...
ClassDecl cd = qq.parseDecl("public class PandaMode { %LM }", (Object) members);
```

**Comment by andrewcmyers** [comment]
It's sounding like the real problem here is under-documentation of the QQ API...

**Comment by anthonycanino1** [comment]
After seeing Jed's workaround it does make much more sense.

On Tue, Jun 30, 2015 at 7:28 AM, Andrew Myers <notifications@github.com>
wrote:

> It's sounding like the real problem here is under-documentation of the QQ
> API...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/polyglot-compiler/polyglot/issues/2#issuecomment-117134552>
> .
>



-- 
Anthony

**Comment by chinawat** [comment]
Thanks, Jed.  I don't remember having success using the list version either, probably because I've been using it all wrong.
